/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;

import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author siddhant
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Chat window ");

        jLabel2.setText("you are talking to a chatbot, say hello to him");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login window"));

        jLabel3.setText("user name");

        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jTextField2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String uname="";
    String prev="";
    String bprev="";
    String quote="";
    
    String[][] chat={
        //0 1
        {"hi","hey","hello","h","hola"},
        {"hi "+uname,"hey! "+uname,"hello " + uname,"hola"},
        //2 3
        {"how are you?","how do you do?","whats up?","whats going on?","are you ok?","how","up","going","hru"},
        {"i am good and you?","i am fantastic","i am fine and you?","i am absolutely fine","who cares :(","i am doing well and you?"},
        //4 5
        {"what is your name?","whats your name?","your name?","who are you?","who's","name","introduction","who","yourself"},
        {"My name is Bot Goswami :)","You can call me Bot bhai","why do you want to know my name?","I am Bot, Bot Goswami!!"},
        //6 7
        {"are","is"},
        {"yes","yes ofcorse","may be","no","nope"},
        //8 9
        {"what"},
        {"i don't know","i have no idea, now don't say get idea :P","i'll tell you about this tommorow"},
        //10 11
        {"why"},
        {"i dont't think i know why","this would be difficult to answer","i'll tell you later"},
        //12 13
        {"can you","can","could","would"},
        {"sorry,i can't","may be","i dont't think so","yes"},
        //14 15
        {"you are"},
        {"what makes you think so!","well, thanks :D","is this a compliment?","are you making fun of me?","may be"},
        //16 17
        {"good","great","yeah","fine","yes","yo","yeah","no"},
        {"great!","good","oh really","oh! yea","but i don't think so"},
        //18 19
        {"tell","say","talk"},
        {"i am actually going to say same thing too","once upon a time there was a man ...hm i forget the remaining part :P ","first promise me you are not going to tell anyone about this ok?","i dont have anything in my mind, you tell something :)"},
        //20 21
        {"bye","good bye","tata","by"},
        {"bye"+uname,"bye\ntake care \nsee you soon :)","khuda hafiz Duaao me yaad rakhna;)"},
        //22
        {"sorry i dont understand","sorry, i don't know about that","i dont have a brain like you!","hmm","ok","good","great","yea you are right"},
        //23
        { "You are repeating yourself","don't you have anything else to say","why the hell you are repeating the same thing","i m getting bored :O"}
            
               
    };
    
    public void response(int u, int i)
    {
                        Random ran=new Random();
                        int k= ran.nextInt(u);
                        if(!bprev.equals(chat[i][k]))
                        {
                             jTextArea1.append("\n-->Bot:\t"+chat[i][k]);
                             bprev=chat[i][k];
                        }
                        else
                        {
                            response(u,i);
                        }
    }
    
    
    
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
               
            int r=0;
            quote=jTextField1.getText();
            
            if(quote.equals(""))
                 jTextArea1.append("\n-->Bot:\t"+uname+", I can't reply if you are sending a blank message! ");
            else if(quote.equals(prev))
                 response(4,23);
            else
            {
                
			jTextField1.setText("");
			jTextArea1.append("\n-->You:\t"+quote);
                        //System.out.println("length " + chat[0].length);
                        quote=quote.trim();
                        quote=quote.toLowerCase();
                        prev=quote;
                        
                        
            //string break into words
             String[] words = quote.split("\\s+");
              //System.out.println("word before loop length : "+ words.length );
             for (int i = 0; i < words.length; i++) {
    
              words[i] = words[i].replaceAll("[^\\w]", "");
              //System.out.println("words after loop: "+words[i]);
               }
            
    out:    for( int l=0; l<words.length;l++)
            {
            for(int i=0;i<chat.length-2;i=i+2)
            {
            for(int j=0;j<chat[i].length;j++)            
            {
                //System.out.println("chat ["+1+"]["+j+"] "+ chat[1][j] +" l= "+l );
                if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==0)            
                { 
                    r=1;
                    break out;
                }
                else if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==2)            
                { 
                    //System.out.println("chat ["+i+"]["+j+"] = "+ chat[i][j] +"word["+l+"] = "+words[l] );
                    r=2;
                    break out;
                }
                else if( ( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==4)            
                { 
                    r=3;
                    break out;
                }
                else if( ( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==6)            
                { 
                    r=4;
                    break out;
                }
                else if( ( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==8)            
                { 
                    r=5;
                    break out;
                }
                else if( ( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==10)            
                { 
                    r=6;
                    break out;
                }
                else if( ( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==12)            
                { 
                    r=7;
                    break out;
                }
                else if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==14)            
                { 
                    r=8;
                    break out;
                }
                 else if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==16)            
                { 
                    r=9;
                    break out;
                }
                 else if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==18)            
                { 
                    r=10;
                    break out;
                }
                else if(( quote.equals(chat[i][j]) || words[l].equals(chat[i][j])) && i==20)            
                { 
                    r=11;
                    break out;
                }
               
            }
            }
     
            }
            //check response
            if(r==1)
            {
              response(3,1);
            }
            else if(r==2)
                    {
                        response(6,3);
                    }
                else if(r==3)
                    {
                        response(4,5);
                    }
                else if(r==4)
                    {
                        response(5,7);
                    }
                else if(r==5)
                    {
                        response(3,9);
                    }
                else if(r==6)
                    {
                        response(3,11);
                    }
                else if(r==7)
                    {
                        response(4,13);
                    }
                else if(r==8)
                    {
                        response(5,15);
                    }
                else if(r==9)
                    {
                        response(5,17);
                    }
                else if(r==10)
                    {
                        response(4,19);
                    }
                else if(r==11)
                    {
                        response(3,21);
                    }
            else
            {
               response(8,22);
            }
            }
            }
            catch(Exception e)
            {
                e.printStackTrace();
                System.out.println(e);
            }
        }
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        uname=jTextField2.getText();
        
         if(uname.equals(""))
             JOptionPane.showMessageDialog(rootPane, "Name can't be null");
         else
         {
             jPanel2.setVisible(false);
             jPanel1.setVisible(true);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
